#!/usr/bin/env python3
"""
Promote best parameters from auto-improve summary into build artifacts.

Outputs:
- Local best executable (for further arena tests)
- Single-variant config JSON
- Best submission source (single-file bundled)
"""

from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path
from typing import Dict


def load_best_defines(summary_path: Path) -> Dict[str, str]:
    with summary_path.open("r", encoding="utf-8") as f:
        summary = json.load(f)
    best = summary.get("best")
    if not best:
        raise RuntimeError(f"No 'best' entry found in {summary_path}")
    defines = best.get("defines")
    if not isinstance(defines, dict) or not defines:
        raise RuntimeError(f"Best entry has no defines in {summary_path}")
    return {str(k): str(v) for k, v in defines.items()}


def build_best_binary(
    root: Path,
    defines: Dict[str, str],
    output_bin: Path,
    source: str,
) -> None:
    output_bin.parent.mkdir(parents=True, exist_ok=True)
    cmd = ["g++", "-std=c++20", "-O2", "-DLOCAL", "-DPSYLEAGUE"]
    for key in sorted(defines.keys()):
        cmd.append(f"-D{key}={defines[key]}")
    cmd += [str(root / source), "-o", str(output_bin)]
    proc = subprocess.run(cmd, text=True, capture_output=True, check=False)
    if proc.returncode != 0:
        raise RuntimeError(f"Best binary build failed:\nCMD: {' '.join(cmd)}\n{proc.stderr}")


def write_best_config(path: Path, source: str, defines: Dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    cfg = {
        "source": source,
        "cxx": "g++",
        "cxxflags": ["-std=c++20", "-O2", "-DLOCAL", "-DPSYLEAGUE"],
        "referee": "referee.jar",
        "build_dir": "arena/best/build",
        "variants": [{"name": "best_auto", "defines": defines}],
    }
    with path.open("w", encoding="utf-8") as f:
        json.dump(cfg, f, indent=2)


def write_best_entry(entry_path: Path, defines: Dict[str, str], source: str) -> None:
    entry_path.parent.mkdir(parents=True, exist_ok=True)
    lines = []
    lines.append("// Auto-generated by tools/promote_best.py")
    for key in sorted(defines.keys()):
        lines.append(f"#define {key} {defines[key]}")
    source_rel = str(Path(source))
    if not Path(source_rel).is_absolute():
        source_rel = str(Path("../") / source_rel)
    lines.append(f'#include "{source_rel}"')
    lines.append("")
    entry_path.write_text("\n".join(lines), encoding="utf-8")


def bundle_submission(root: Path, entry_path: Path, output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    cmd = [
        "python3",
        str(root / "tools" / "bundle_submission.py"),
        str(entry_path),
        "--output",
        str(output_path),
    ]
    proc = subprocess.run(cmd, text=True, capture_output=True, check=False)
    if proc.returncode != 0:
        raise RuntimeError(f"Bundle failed:\nCMD: {' '.join(cmd)}\n{proc.stderr}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Promote best auto-improve parameters")
    parser.add_argument(
        "--summary",
        default="arena/auto/latest_summary.json",
        help="Path to auto-improve summary JSON",
    )
    parser.add_argument(
        "--source",
        default="brain.cpp",
        help="Entry source compiled/bundled with best defines",
    )
    parser.add_argument(
        "--best-config",
        default="arena/auto/best_config.json",
        help="Path to write single-variant best config JSON",
    )
    parser.add_argument(
        "--best-bin",
        default="build/brain_best",
        help="Path for best local executable",
    )
    parser.add_argument(
        "--best-entry",
        default="build/best_entry.cpp",
        help="Temporary C++ entry with injected #defines",
    )
    parser.add_argument(
        "--best-submission",
        default="build/bot_submission_best.cpp",
        help="Output bundled submission source with best defines",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    root = Path(__file__).resolve().parents[1]

    summary_path = (root / args.summary).resolve()
    best_cfg_path = (root / args.best_config).resolve()
    best_bin_path = (root / args.best_bin).resolve()
    best_entry_path = (root / args.best_entry).resolve()
    best_submission_path = (root / args.best_submission).resolve()

    defines = load_best_defines(summary_path)
    write_best_config(best_cfg_path, args.source, defines)
    build_best_binary(root, defines, best_bin_path, args.source)
    write_best_entry(best_entry_path, defines, args.source)
    bundle_submission(root, best_entry_path, best_submission_path)

    print(f"[promote] defines: {defines}")
    print(f"[promote] best config: {best_cfg_path}")
    print(f"[promote] best binary: {best_bin_path}")
    print(f"[promote] best submission: {best_submission_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
